### ISSUE TITLE
Deprecated features

### ISSUE THREAD

**Issue by vi** [Nercury/tokio-proxy-rs#1]
If I remove `Cargo.lock`, I see warnings about deprecated features about features moved from tokio-core to tokio-io.

As this project provides a nice tutorial example for Tokio, I think it should be fixed to stay up to date with Tokio.

**Comment by Nercury** [comment]
Hi!

Thanks for noticing this. This was my first attempt to write code with tokio, and I always wondered if it was correct. And it looks like it is not, because [the official proxy example](https://github.com/tokio-rs/tokio-core/blob/master/examples/proxy.rs) has an additional handling for shutdown. That was probably the reason why this proxy worked on windows but was flaky on osx.

Therefore I think it would be best to remove this repo, because [the official example will be maintained and updated better than I could do it](https://github.com/tokio-rs/tokio-core/blob/master/examples/proxy.rs).

**Comment by vi** [comment]
Yes, shutdown works poorly, unlike in the linked example.

The repository should be retained (for searching), but with the deprecation status in description and the link to that example in README.
